---
apiVersion: "v1"
data:
  elastic-search-service-name: "elasticsearch"
  elastic-search-service-port: "9200"
  hunting-interval: "3"
kind: "ConfigMap"
metadata: {}
labels: {}
name: "${fabric8.service.name}"
